version: '3.5'

services:

  rinha-pg:
    image: postgres
    container_name: rinha-pg
    hostname: rinha-pg
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
    environment:
      - POSTGRES_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRES_HOST=${POSTGRESQL_HOST}
    command: postgres -c 'max_connections=33'
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    networks:
      - rinha-backend-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1.5GB"

  node1: &node
    image: gpmarchi/rinha-backend-node:latest
    container_name: rinha-node1
    hostname: rinha-node1
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3333:3333
    expose:
      - ${PORT}
    networks:
      - rinha-backend-network
    depends_on:
      - rinha-pg
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.6GB"
 
  node2:
    <<: *node
    container_name: rinha-node2
    hostname: rinha-node2
    ports:
      - 3334:3334
  
  # node2:
  #   image: gpmarchi/rinha-backend-node:latest
  #   container_name: rinha-node2
  #   hostname: rinha-node2
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - PORT=${PORT}
  #     - DATABASE_URL=${DATABASE_URL}
  #   # ports:
  #   #   - 3333:3333
  #   expose:
  #     - ${PORT}
  #   networks:
  #     - rinha-backend-network
  #   depends_on:
  #     - rinha-pg
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.25"
  #         memory: "0.6GB"
  
  nginx:
    image: nginx:1.15.0-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
    ports:
      - "9999:9999"
    networks:
      - rinha-backend-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.3GB'

networks:
  rinha-backend-network:
    driver: bridge