version: '3.5'

services:

  rinha-pg:
    image: postgres
    container_name: rinha-pg
    hostname: rinha-pg
    restart: always
    env_file:
      - .env
    # ports:
    #   - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
    expose:
      - ${POSTGRESQL_PORT}
    environment:
      - POSTGRES_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRES_HOST=${POSTGRESQL_HOST}
    # command: postgres -c 'max_connections=450'
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    network_mode: host
    # networks:
    #   - rinha-backend-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1.5GB"

  node1: &node
    image: gpmarchi/rinha-backend-node:latest
    container_name: rinha-node1
    hostname: rinha-node1
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      # - PORT=${PORT}
      - PORT=3333
      - DATABASE_URL=${DATABASE_URL}
    # ports:
    #   - 3333:3333
    expose:
      # - ${PORT}
      - 3333
    network_mode: host
    # networks:
    #   - rinha-backend-network
    depends_on:
      - rinha-pg
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000    
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.6GB"
 
  node2:
    <<: *node
    container_name: rinha-node2
    hostname: rinha-node2
    environment:
      - PORT=3334
    expose:
      - 3334
    # ports:
    #   - 3334:3334
  
  nginx:
    image: nginx:1.15.0-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
    # ports:
    #   - "9999:9999"
    expose:
      - 9999
    network_mode: host
    # networks:
    #   - rinha-backend-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.3GB'

# networks:
#   rinha-backend-network:
#     driver: bridge