version: '3.5'

services:

  rinha-pg:
    image: bitnami/postgresql
    container_name: rinha-pg
    hostname: rinha-pg
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
    networks:
      - rinha-backend-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1.5GB"

  node1:
    image: gpmarchi/rinha-backend-node:latest
    container_name: rinha-node1
    hostname: rinha-node1
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3333:3333
    expose:
      - ${PORT}
    networks:
      - rinha-backend-network
    depends_on:
      - rinha-pg
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.6GB"

networks:
  rinha-backend-network:
    driver: bridge