apiVersion: v1
kind: ConfigMap
metadata:
  name: rinha-env
data:
  NODE_ENV: "production"
  PORT: "3333"
  DATABASE_URL: "postgresql://postgres:postgres@192.168.0.36:5432/rinha2023?schema=public&connection_limit=4&connect_timeout=5"
